### ISSUE TITLE
Length has to be provided when creating DataMatrix from keyword sequence

### ISSUE THREAD

**Issue by egaudrain** [smathot/python-datamatrix#15]
I'm trying to create a DataMatrix row by row and it is proving frustratingly difficult. After many attempts I decided to create a `dict` of lists and pass that as `**kwargs` to the DataMatrix constructor. But that only works if we give the correct length keyword.

For instance:
```python
>>> d = DataMatrix(length=3, a=[1,2,3], b=[4,5,6])
```
works fine.

But omitting the length argument gives an error:
```python
>>> d = DataMatrix(a=[1,2,3], b=[4,5,6])
[...]
ValueError: Sequence length does not match DataMatrix
```
Since this is constructor method, probably the DataMatrix can infer the length from the keyword arguments given that it is checking their length to raise an error anyway...?

But what would be most reassuring and convenient would be to be able to build a DataMatrix from a list of dictionaries (like in pandas) rather than a dictionary of lists... The native csv Python module `DictReader` operates that way, and this is the correct approach when one wants to make sure the data within a row always remains together and is immune to spurious index shifts across columns.

**Comment by smathot** [comment]
Thanks for this. Indeed, it would be good if a `DataMatrix` could be a) initialized in the same way as a `DataFrame`, and b) if the length would be inferred if data is passed as `list` objects. This will be easy to implement, so I'll do that for a next release. For now, you can already use the hacky `_fromdict()` method, which is intended for internal use but does work.

```python
from datamatrix import DataMatrix
# currently works but is ugly
dm = DataMatrix()._fromdict({'x': [1, 2], 'y': [3, 4]})
# dataframe-style (does not work)
dm = DataMatrix({'x': [1, 2], 'y': [3, 4]})
# list-style (does not work without specifying length)
dm = DataMatrix(x=[1, 2], y=[3, 4])
```
