### ISSUE TITLE
_blinkreconstruct_recursive() stops looking for blinks when first blink is too long

### ISSUE THREAD

**Issue by JulietaLaurino** [smathot/python-datamatrix#17]
If i'm not wrong, when implementing the recursive blink-reconstruction algorithm, `_blink_points` returns `None` if the blink is too long. This results in `_blinkreconstruct_recursive` interpreting that there are no more blinks and thus stops the recursive algorithm. That's why if the first detected blink is too long, the algorithm does not work properly because it ignores any other future blinks. 
I solved this in my local script but I think it would be good to add the change to the library!

**Comment by smathot** [comment]
Thanks, you're right. That's a bug clearly. I can fix this myself, but you can also submit a PR with your fix if you want?

**Comment by smathot** [comment]
Closed in #18
