### ISSUE TITLE
blinkreconstruct() add NANs but doesn't  interpolate

### ISSUE THREAD

**Issue by courtneygoodridge** [smathot/python-datamatrix#20]
Hi Sebastiaan, 

Many thanks for your open source code, its super helpful. I have a question which might be my lack of understanding rather than any bug. 

I am using the `blinkreconstruct()` function to remove blinks from my pupil diameter data. An example trial from my data looks like this:

<img width="143" alt="image" src="https://github.com/open-cogsci/datamatrix/assets/44811378/b0704844-ece3-40e8-a74f-2a0fe4747451">

With time on the x axis and pupil diameter on the y axis

![image](https://github.com/open-cogsci/datamatrix/assets/44811378/fe475d42-375c-44b4-8620-43386237e841)

After converting my data into a series, I use the `blinkreconstruct()` function and plot the reconstructed result:

```
# recontructing pupil
pupil_dm.recon = srs.blinkreconstruct(pupil_dm.diameter, mode = "advanced")
# plotting
x = pupil_dm.time[0]
y1 = pupil_dm.recon[0]
plt.plot(x, y1)
plt.ylim(0, 7)
```
![image](https://github.com/open-cogsci/datamatrix/assets/44811378/675e650e-0c59-4960-9252-485612366dc1)

As you can see, this removes a lot of data and doesn't seem to interpolate between the gaps. If I set the `gap_margin` argument lower than the 20 default, I retain more data but still have gaps that aren't interpolated:

```
# recontructing pupil
pupil_dm.recon = srs.blinkreconstruct(pupil_dm.diameter, gap_margin = 5, mode = "advanced")
```
![image](https://github.com/open-cogsci/datamatrix/assets/44811378/7f90339b-665a-4c87-a5bc-13b47602c251)

Looking at the recon variable seems to suggests that the only thing happening is that extra NANs are created, the number of which is dictated by whatever I set `gap_margin`. After reading your paper (Mathôt, S., & Vilotijević, A. (2023). Methods in cognitive pupillometry: Design, preprocessing, and statistical analysis. Behavior Research Methods, 55(6), 3055-3077.), this isn't how I thought the function worked. 

Am I misunderstanding something?  Perhaps there is a setting I'm not implementing in order to get the cubic/linear interpolation. I should add that my units are in mm - i have converted to AU but the same thing happens. 

Any advice would much appreciated, thank you. 

Courtney

**Comment by smathot** [comment]
Hi @courtneygoodridge ,

The default parameters of the `blinkreconstruct()` function have been finetuned for the EyeLink 1000 recording in arbitrary units and with a sampling rate of 1000 Hz. I suspect that you are simply using a different eye tracker or perhaps different settings for the EyeLink. Is that correct? In that case, you need to manually tweak the parameters through trial and error until they make sense for your data.

Another thing to consider is that this algorithm is mainly useful for high-frequency and high-quality recordings in which rapid changes in pupil size can be reliably determined. If you have low-frequency and/ or low-quality recordings (?), then you may be better of with a simpler algorithm in which (for example) you exclude outliers based on some threshold.

— Sebastiaan

**Comment by courtneygoodridge** [comment]
Hi @smathot 

Thank you for your quick response. Indeed, we use a different eye tracker that samples at 60 Hz. I guess trial and error is the only way forward with this particular algorithm? I'll have a look around to see if there are alternatives. 

Thanks again, 

Courtney

**Comment by smathot** [comment]
> I guess trial and error is the only way forward with this particular algorithm? I'll have a look around to see if there are alternatives.

Yes I'm afraid it is. Good luck! I'm closing this issue, because it's not related to a bug in DataMatrix, but feel free to post further questions on the [support forum](https://forum.cogsci.nl/).
